### PR TITLE
Modernize code.

### PR DESCRIPTION
**Pull request by vaijira**
* Replace try! by ?
* Update library references.
* Fix compilation warnings.
* Fix test case.

### CODE REVIEW

**Comment by Proksima** [comment]
Thank you for the pull request, I will inspect it and merge it over the weekend.

**Comment by Proksima** [comment]
Looks amazing! Thank you for taking time to do this. I hadn't looked into this project into a long time, but it looks like there is a few users actively using it. I am sure they will appreciate the bump in dependency versions!

**Comment by Proksima** [comment]
I went ahead and publish the update on crates.io for your convenience.

I must admit that if I was re-writing this crate now, I would probably have made it async. That being said I will keep accepting PRs as long as they are useful to some!

Thanks again!

**Comment by vaijira** [comment]
Thanks to you.

**Pull request merged**
