### PR TITLE
fix send data query result vector

### PR DESCRIPTION
**Pull request by pmd3d**
i am new to rust. i tried the example code from the quandl github home page that attempts to get all the feb 2016 aapl prices but it only returned a vector of length 1. i added a test and made a fix. i'm not experienced with this so if i am missing anything please let me know. thanks.

### CODE REVIEW

**Comment by Proksima** [comment]
Thank you for your interest in the library. I know it is broken and that is due to the fact this code was meant to abuse Quandl's API to allow good throughput even without premium membership. However, barely a month after I starting using the library in my research they introduced several API changes (limits) that made the code useless.

I actually have (had? didn't use in a while) an updated version that works, but I deemed it too unstable/hackish to be published.

Give me a week, and I will go back to it, shrink it to its stable (working) core and publish an updated version that I am willing to maintain. Honestly, I was waiting for confirmation other people are using it to make the effort as I do not need it myself anymore.

**Comment by pmd3d** [comment]
ok. thanks for the history.

**Comment by pmd3d** [comment]
Quandl announced their WIKI data source is no longer being maintained. So I'm not planning on accessing Quandl now.

**Comment by Proksima** [comment]
This PR is old and the original author was no longer interested in the project anyway. Closing.

**Pull request closed without merging**
